### ISSUE TITLE
Pick up accounts and files

### ISSUE THREAD

**Issue by andreidum** [LaunchPlatform/beanhub-forms#2]
Hello,
I'm running locally  beanhub-cli 2.1.1 and beanhub-forms 0.1.3
I've created the form below and launched the server, however the file and accounts fields are not populated (dropdowns are empty and displaying "No Option").. Can you please comment if beanhub-forms is supposed to pick up the files and accounts from my main.bean or if it supports a hard-coded list of values? I couldn't find any documentation for this field type.

```
forms:
- name: balance-account
  display_name: "Balance account"
  fields:
  - name: date
    type: date
    display_name: "Date"
    required: true
  - name: file
    type: file
    display_name: "File"
    required: true
  - name: account
    type: account
    display_name: "Balance account"
    default: "Assets:EUR:Cash"
    required: true
  - name: balance
    type: number
    display_name: "Balance value"
    required: true
  - name: currency
    type: str
    display_name: "Currency"
    default: "EUR"
    required: true
  operations:
  - type: append
    file: "main.bean"
    content: |
      {{ date }} balance {{ account }} {{balance}} {{currency}}

```
